### ISSUE TITLE
use two pinches to pull a scrap into two copies of itself

### ISSUE THREAD

**Issue by adamwulf** [adamwulf/loose-leaf#313]
http://stackoverflow.com/questions/9470493/transforming-a-rectangle-image-into-a-quadrilateral-using-a-catransform3d/12820877#12820877

pinch a scrap twice to hold onto it, and then stretch it with the polygon info above so that it looks like its being stretched and skewed in the direction of the pull
- [x] support stretching 2d transformed views
- [x] support restarting the gesture after some touches lifted
- [x] integrate into loose leaf
- [x] when triggering the stretch gesture quickly, it seems a leftover pan gesture triggers before/during the stretch gesture, which causes the scrap to revert back to its original location during the animation, which screws up calculations when ending the stretch
- [x] stretch a scrap, lift all but two fingers, and move those fingers while the animation is mid-flight. the scrap will land where it was when the movement started. i think.
- [x] put a scrap on the right/left edge of the paper. bezel the page. the scrap pan should cancel (not get pushed to other page). re-panning the scrap should work fine and not fail to the drawing gesture
- [x] fix #346 so that both pan gestures can't hold the same scrap
- [ ] adjust stretch gesture to trigger off of 4 valid touches from either pan gesture
  - this way, when a stretch causes a pan touch to fall outside the scrap, it still counts towards the next stretch
- [ ] minimize or remove the bounce animation if the stretch was very small
- [x] determine the size of the stretch so that we can split the object into two at the right moment
- [ ] after the animation, pop the scrap to the correct location for the two touches, instead of re-linking the touches at the new anchor point. this way, stretching the same scrap multiple times won't adjust the anchor point of the two leftover touches
- [x] stretch gesture doesn't play nice with page pan. Stretch scrap to new position, the pan page, it pops to new location.
- [x] problem with page pan and scrap stretch
  1. hold scrap and move it into the scrap container
  2. only hold 2 fingers on scrap after 1, then stretch scrap
  3. not sure what to do here, but the scrap stretch and page pan both seem to use the last 2 touches.
  4. i probably need to refactor how the page pan gesture works a bit, since it sets state incorrectly
- [x] fix page bouncing #351
- [x] fix scrap stretching sometimes jumping the scrap to wrong location #352
