### ISSUE TITLE
Support multiple stacks

### ISSUE THREAD

**Issue by adamwulf** [adamwulf/loose-leaf#44]
For some reason, the branch at 1f49466aa doesn't show more than 20 pages in the visible stack when loading.
1. load app -> choose to view last page in the document so that 100% are in visible stack and 0 in hidden. should be > 20 pages
2. exit app
3. relaunch
4. subviews shows all > 20 pages, but view inspector only shows 20.
5. add page button
6. only visible 20 pages will be written to disk, the other pages are now lost

it's the strangest thing, i've no idea what's going on, and hopefully a bisect on the multiple-stacks branch will track it down.
# 

Just stack then in list mode, separated by a line/header. Easily drag pages between stacks. Delete/export entire stacks from their header.

Very similar to events in iPhoto
- [x] look through other managers that are shared
- [x] find other places that save the stack manager as the delegate
- [x] load into list view from fresh launch
- [x] switch between lists while maintaining memory performance
- [x] when switching stacks, it's loading the wrong page thumbnail in list mode for the current top page. it's loading the base ink thumbnail, but needs the scrapped thumbnail. might be an artifact of loading into page view instead of list view (?)
- [x] ability to add stack default to empty three page documents for new stacks
- [x] support arbitrary number of stacks
- [x] ability to delete stacks
- [x] to copy a page to a stack, use #501 first the move one of the duplicates
- [x] simple UI for browsing stacks
- [x] differentiate the active stack vs non-active stacks
- [x] animation when switching stacks
- [x] allow pages to be rotated slightly when in collapsed view, but turn off the anti-aliasing when in normal list mode, otherwise it's too laggy
- [x] ensure all lists will load their page thumbnails when visible in collapsed view
- [x] performance check for at least 1000 stacks (related to #1632)
- [x] add stack button to add empty stack
- [x] import document button #1632
- [x] long press or use two fingers to pick up a stack to reorder it in the list, just like in list mode for pages
- [x] swipe to the left a little to show duplicate / delete / export buttons
- [x] swipe to the left a lot to delete
- [x] button in list view (top right?) to immediately transition to collapsed view regardless of scroll offset
- [x] tutorial button at bottom of collapsed view
- [x] handle scenario where user is in multiple stacks view, closes the app, and then Open In's to Loose Leaf with an image or pdf. We should probably auto-create a new stack and show that stack. Alternatively, show the import stack menu / option without auto-creating it

Possible features, needs thought:
- [x] Ability to name a document and for that name to show in collapsed / list views
